apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: endococdelab-io-issuer
  namespace: kube-system
spec:
  acme:
    email: $GCP_USER_CONTACT
    # Test / Staging LetsEncrypt URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Production LetsEncrypt URL
    #server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: endocodelab-demo-letsencrypt
    dns01:
      providers:
      - name: clouddns
        clouddns:
          serviceAccountSecretRef:
            name: clouddns-svc-secret
            key: credentials.json
          project: $GCP_DNS_PROJECTNAME